### ISSUE TITLE
[Feature Request]: Right click to copy link

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/joplin-rich-markdown#22]
[requested on the forum](https://discourse.joplinapp.org/t/plugin-rich-markdown/15053/249)

This is something I'd like to support, and would accept a PR for. The only issue I can foresee is that I'm not sure if there is a good way to dynamically change the context menu based on what's being clicked.

What would be nice is the ability for a plugin developer to provide a function that gets applied to the text under the cursor which would determine if the menu item appears or not. I think similar functionality is already available and could maybe be extended for this use.

**Comment by laurent22** [comment]
I had actually started making some changes towards this, because I wanted to add support for saving an image from the editor, but didn't go very far.

I think the current approach for context menu is not ideal. Instead of declaring in advance the menu, the app should call some function in the plugin, and the menu could be built at that point. With that method the plugin can display different menus depending on the context.

If I remember well the tricky part was to change some sync calls to async in the app, so that it's possible to call the plugin and wait for the result.

**Comment by CalebJohn** [comment]
Fixed in #30
