### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by jerrylususu** [CalebJohn/joplin-rich-markdown#34]
Not sure why, but the highlight function doesn't seem to work in editor mode, even though `==mark==` is already enabled.

Env:
- Joplin: 2.6.10 (98fba37)
- Plugin: v0.8.3

![image](https://user-images.githubusercontent.com/17522475/149780059-fbd3a2ca-f986-4b36-a172-5a7ffe4f7e02.png)

**Comment by CalebJohn** [comment]
Thanks for reporting this, this is an issue with the way mark is configured in the settings. I accidentally made it require the "extra CSS" option. You can get the highlighting now if you toggle that option, otherwise [it will be fixed in the next release](https://github.com/CalebJohn/joplin-rich-markdown/issues/32).
