### ISSUE TITLE
Markdown hightlight `==` didn't work

### ISSUE THREAD

**Issue by LintaoAmons** [CalebJohn/joplin-rich-markdown#35]
- I'm not sure if this is only my issue. But this syntax didn't work in my joplin.

    ![image](https://user-images.githubusercontent.com/95092244/150459902-14b4c019-b014-470a-ac8e-fbc60a84d6aa.png)

- Also I have enabled this config

    ![image](https://user-images.githubusercontent.com/95092244/150459921-80300605-b239-4b00-97f2-60ec23871a4b.png)

**Comment by CalebJohn** [comment]
Hi @LintaoAmons, indeed that's my mistake, you will also need to enable the "extra CSS" option in the Rich Markdown plugin settings. This will be fixed in the next release. You can check #32 and #34 for more information.

I'll leave this issue open as it seems many users are running in to this issue.

---

Just an aside, but this issue has existed for over a month and it's now gotten 3 reports in the last week!

**Comment by LintaoAmons** [comment]
One thing to mention:

the highlight color may need to adapt to the dark theme. I just enable the "extra CSS" option, found the highlighted background made me hard to recognize the content.

![image](https://user-images.githubusercontent.com/95092244/150467235-f6088b9c-7a7d-40cb-a402-ce77e80dfa42.png)

**Comment by CalebJohn** [comment]
The color used is the same as the one in the renderer. Is it possible that you have some custom css that's overriding the color?
If not, please let me know what version of Joplin and what version of the plugin you use.

For reference, here is how it looks on my machine
![image](https://user-images.githubusercontent.com/2179547/150469629-2e737dcb-dca7-4a3f-a701-c982ba248227.png)

**Comment by LintaoAmons** [comment]
Oh， Yes， I have customized the text color. 

Is there a way that I can do some customization only to the highlight block?

**Comment by CalebJohn** [comment]
Yes, it just uses regular css

example
```css
.cm-rm-highlight {
    color: black !important;
}
```
