### ISSUE TITLE
[Feature Request] Swap line up/down in rich editor

### ISSUE THREAD

**Issue by Aerosmite** [CalebJohn/joplin-rich-markdown#65]
It would be great if you could implement the "Swap line up" and "Swap line down" command in the editor, as I often re-organize my though when I am writing and moving line by copy/pasting is quite slow... The shortcut for deleting/duplicating lines would also be super useful too!
Although this feature is "just" about finding the correspondence between the richtext and markdown editor and executing the shortcut in the latter, I do see a few watch points:
- Potential shortcuts conflicts with the [TinyMCE keybindings](https://www.tiny.cloud/docs/advanced/keyboard-shortcuts/)
- If cases to distinguish between soft and hard breaks when moving full or part of a paragraph
- Preserve numbered lists (see [this discussion](https://discourse.joplinapp.org/t/is-it-possible-to-swap-lines-of-numbered-lists/23034))

Thanks for the amazing plugin, really helped me switch from Mac to Windows easily.

**Comment by CalebJohn** [comment]
Hi @Aerosmite 
Thanks for the interest in this plugin. 

The rich markdown plugin just adds some styling to the markdown editor so that people like me can edit their notes in plain text, but see something a little more colorful.

The "richtext" editor (based on tinymce) is a core feature of the Joplin application, I would suggest you make this request there.

All the best!
