### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by Entreprenerdz** [CalebJohn/joplin-rich-markdown#7]
Sorry for the n00b question here, but while I'm a developer, I'm new to Joplin.

Normally for a Joplin plugin, I get one of:
* jpl - great for my Windows/Mac/Android devices (actually, haven't checked Android yet)
* npm - great for my mac as I use npm there, too bad for Windows

I see ppl talking about installing it, yet there's nothing in your ReadMe here, the discourse, or the files themselves.  Do I need to compile the jpl and if so how or just put in a folder and again, if so, where?

Thanks.  Excited to try this out, given I"m currently spending more time in Joplin than I am in Atom these days.

**Comment by CalebJohn** [comment]
Hi @Entreprenerdz, no worries, this has come up before and i really should include install instructions in the readme.
Initially plugins required a jpl file to install because the plugin system was in beta and the install procedure wasn't finished. Now (v1.6.1 and up) you can easily install plugins through the Joplin settings.
Just open the options menu Tools -> Options (Joplin -> Preferences on mac) and select plugins. It should be about halfway down the side bar.
In this menu you'll see a list of your currently installed plugins (if you have any) and a search bar. You can use this searchbar to search the name of any plugin and get a one click install. You'll be prompted to restart the application once the plugin has downloaded. Once you restart everything will be installed and setup!

Alternatively, you can download a jpl file and place it in the plugin directory of your Joplin install. But that's more of a development/debugging way to install.

I hope that all makes sense. I'll be updating the readme soon so there isn't any more confusion.

**Comment by Entreprenerdz** [comment]
It makes total sense!!  Which is why I can't figure out why ONLY on my Macs, the search box is disabled.

I've been using .jpl files as a workaround and to be honest, it's kinda preferred as I download them into a sync'd folder and that makes it very easy to update the PC and other mac.

Here's what I'm seeing on my Mac... (not sure if you can tell but I assure you it's disabled/greyed out) if you don't happen to know of a fix for this (to be able to search for your plugin), any chance you have a .jpl of it kicking around?

<img width="725" alt="image" src="https://user-images.githubusercontent.com/17835969/117579010-e56ab480-b0a5-11eb-8214-8fbb6367da0b.png">

**Comment by CalebJohn** [comment]
That's interesting, I wasn't aware of this bug. In case you still need it, i do provide a jpl file with the most recent changes. Which means it sometimes tracks ahead of the release version.
https://github.com/CalebJohn/joplin-rich-markdown/blob/main/publish/plugin.calebjohn.rich-markdown.jpl
